baseURL = "pages.github.service.anz/carpeggj/talks-go/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true